
services:
    db:
        image: postgres:16
        container_name: postgres_db
        restart: always
        ports:
          - "5433:5432"
        environment:
            POSTGRES_USER: admin
            POSTGRES_PASSWORD: 123123
            POSTGRES_DB: linked_mag_db
        volumes:
            - postgres_data:/var/lib/postgresql/data
    
    backend:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: linked_mag_node_backend
        restart: always
        ports:
          - "3000:3000"
        volumes:
            - .:/app
            - /app/node_modules
        working_dir: /app
        depends_on:
            db:
                condition: service_healthy
        environment:
            DB_HOST: db
            DB_PORT: 5432
            DB_USER: admin
            DB_PASSWORD: 123123
            DB_NAME: linked_mag_db
        command: ["npm", "run", "dev"]

volumes:
    postgres_data:
