'use strict';

module.exports = {
  async up(queryInterface, Sequelize) {
    await queryInterface.bulkInsert('companies', [
      {
        nameCompany: 'Tech Solutions',
        emailCompany: 'contact@techsolutions.com',
        phoneCompany: 3001234567,
        NIT: 123456789,
        addressCompany: 'Calle 123 #45-67',
        password: 'hashedpassword1',
        deparmentCompany: 'Magdalena',
        cityCompany: 'Santa Marta',
        descriptionCompany: 'Empresa de soluciones tecnológicas.',
        profileImage: 'https://example.com/profile1.jpg',
        banner: 'https://example.com/banner1.jpg',
        selectTypeCompany: 'Privada',
        selectEconomicSector: 'Tecnología',
        statusRegister: 'Pendiente',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nameCompany: 'Innovatech',
        emailCompany: 'info@innovatech.com',
        phoneCompany: 3019876543,
        NIT: 987654321,
        addressCompany: 'Carrera 45 #67-89',
        password: 'hashedpassword2',
        deparmentCompany: 'Atlántico',
        cityCompany: 'Barranquilla',
        descriptionCompany: 'Empresa innovadora en tecnología.',
        profileImage: 'https://example.com/profile2.jpg',
        banner: 'https://example.com/banner2.jpg',
        selectTypeCompany: 'Pública',
        selectEconomicSector: 'Innovación',
        statusRegister: 'Aprobado',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nameCompany: 'EcoLogistics',
        emailCompany: 'contact@ecologistics.com',
        phoneCompany: 3025551234,
        NIT: 555666777,
        addressCompany: 'Avenida 10 #20-30',
        password: 'hashedpassword3',
        deparmentCompany: 'Cundinamarca',
        cityCompany: 'Bogotá',
        descriptionCompany: 'Logística ecológica y sostenible.',
        profileImage: 'https://example.com/profile3.jpg',
        banner: 'https://example.com/banner3.jpg',
        selectTypeCompany: 'Privada',
        selectEconomicSector: 'Logística',
        statusRegister: 'Rechazado',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nameCompany: 'AgroCol',
        emailCompany: 'info@agrocol.com',
        phoneCompany: 3034445566,
        NIT: 112233445,
        addressCompany: 'Finca El Progreso',
        password: 'hashedpassword4',
        deparmentCompany: 'Antioquia',
        cityCompany: 'Medellín',
        descriptionCompany: 'Empresa dedicada al sector agrícola.',
        profileImage: 'https://example.com/profile4.jpg',
        banner: 'https://example.com/banner4.jpg',
        selectTypeCompany: 'Privada',
        selectEconomicSector: 'Agricultura',
        statusRegister: 'Pendiente',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nameCompany: 'FinanzasYA',
        emailCompany: 'contacto@finanzasya.com',
        phoneCompany: 3043332211,
        NIT: 998877665,
        addressCompany: 'Calle 50 #60-70',
        password: 'hashedpassword5',
        deparmentCompany: 'Valle del Cauca',
        cityCompany: 'Cali',
        descriptionCompany: 'Servicios financieros y asesorías.',
        profileImage: 'https://example.com/profile5.jpg',
        banner: 'https://example.com/banner5.jpg',
        selectTypeCompany: 'Pública',
        selectEconomicSector: 'Finanzas',
        statusRegister: 'Aprobado',
        createdAt: new Date(),
        updatedAt: new Date(),
      },
      {
        nameCompany: 'SaludTotal',
        emailCompany: 'info@saludtotal.com',
        phoneCompany: 3052223344,
        NIT: 776655443,
        addressCompany: 'Carrera 100 #20-50',
        password: 'hashedpassword6',
        deparmentCompany: 'Santander',
        cityCompany: 'Bucaramanga',
        descriptionCompany: 'Servicios de salud integral.',
        profileImage: 'https://example.com/profile6.jpg',
        banner: 'https://example.com/banner6.jpg',
        selectTypeCompany: 'Privada',
        selectEconomicSector: 'Salud',
        statusRegister: 'Pendiente',
        createdAt: new Date(),
        updatedAt: new Date(),
      }
    ]);
  },

  async down(queryInterface, Sequelize) {
    await queryInterface.bulkDelete('companies', null, {});
  }
};